version: '3.8'
services:
    api:
        container_name: api
        build: .
        env_file:
            - .env
        ports:
            - "8888:8080"
        volumes:
            - .:/usr/src/app
        command: go run main.go
        depends_on:
            - postgres
        networks: ["hacktiv8"]
        
    postgres:
        container_name: postgres
        image: postgres:alpine
        volumes:
            - postgres-db:/var/lib/postgresql/data
        networks: ["hacktiv8"]
        ports:
            - "5422:5432"
        environment:
            - PGUSER=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        restart: always

networks:
    hacktiv8:

volumes:
    postgres-db: