version: '3.8'
services:
    api:
        build: .
        env_file:
            - .env
        ports:
            - "8888:8080"
        volumes:
            - .:/usr/src/app
        command: go run main.go
        depends_on:
            - db
        networks: ["hacktiv8"]
        
    db:
        container_name: postgres
        image: postgres:16
        env_file:
            - .env
        volumes:
            - postgres-db:/var/lib/postgresql/data
        networks: ["hacktiv8"]
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}
        restart: always

networks:
    hacktiv8:

volumes:
    postgres-db: