name: CI
on:
    push:
        branches: ["main"]
jobs:
    build:
        environment: production
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Connect to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_TOKEN }}

            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Build and push
              uses: docker/build-push-action@v4
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKER_USERNAME }}/hacktiv8-final-project4:latest
    deployment:
        needs: build
        environment: production
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to Server
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SERVER }}
                  username: ${{ secrets.SERVER_USERNAME }}
                  password: ${{ secrets.SERVER_PASSWORD }}
                  port: ${{ secrets.SERVER_PORT }}
                  script: |
                      whoami
                      # Login To Docker Hub
                      docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}

                      # Stop running container
                      docker stop  ${{ vars.IMAGE_NAME }}

                      # Remove container
                      docker rm ${{ vars.IMAGE_NAME }}

                      # Pull latest image
                      docker pull ${{ secrets.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:latest

                      # Run image
                      docker run -d -p 1213:1213 --name ${{ vars.IMAGE_NAME }} ${{ secrets.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:latest
